version: "3"

services:
  backend:
    build: 
      dockerfile: ./backend/Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:4.4
    restart: always
    ports: 
      - "27017:27017"
  redis:
    image: redis:6.2
    ports:
     - "6379:6379"
